services:
  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.format=common"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /var/log/traefik:/var/log/traefik
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Dashboard con Auth + Seguridad + Rate Limit
      - "traefik.http.routers.traefik-dashboard.rule=Host(`dashboard.dani.gonzalonazareno.org`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=dani:$$apr1$$GHluLg7S$$aOC0vhv9hHZz3.Ri0m1kf."
      - "traefik.http.routers.traefik-dashboard.middlewares=dashboard-auth,secure-headers@file,limit-peticiones@file"

  web:
    build: ./app
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-router.rule=Host(`www.dani.gonzalonazareno.org`)"
      - "traefik.http.routers.web-router.entrypoints=websecure"
      - "traefik.http.routers.web-router.tls=true"
      - "traefik.http.services.web-service.loadbalancer.server.port=80"
      # Web con Seguridad + Rate Limit
      - "traefik.http.routers.web-router.middlewares=secure-headers@file,limit-peticiones@file"

networks:
  web:
    driver: bridge
