#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        iif lo accept
        ct state established,related accept
	tcp dport 22 ct state new accept
	ip protocol icmp icmp type echo-request accept
	# Aceptar logs de la red interna (TCP y UDP)
	ip saddr { 192.168.0.0/24, 172.16.0.0/16, 172.18.0.0/16 } tcp dport 514 accept
	ip saddr { 192.168.0.0/24, 172.16.0.0/16, 172.18.0.0/16 } udp dport 514 accept
    }

    chain output {
        type filter hook output priority 0; policy drop;

	oif lo accept
	ct state established,related accept
        tcp dport 22 ct state new accept
        tcp dport 80 ct state new accept
        tcp dport 443 ct state new accept
        udp dport 53 ct state new accept
        tcp dport 53 ct state new accept
        ip protocol icmp accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }
}
