#!/usr/sbin/nft -f

flush ruleset

# Firewall Horus
table inet filter {

    chain input {
        type filter hook input priority 0; policy drop;
        iif lo accept

        # Conexiones ya establecidas o relacionadas
        ct state established,related accept

        # SSH, HTTP, HTTPS, CORREO, DNS
        tcp dport 22 ct state new accept
        tcp dport 25 ct state new accept
        tcp dport 80 ct state new accept
        tcp dport 443 ct state new accept
        udp dport 53 ct state new accept
        tcp dport 53 ct state new accept
	ip protocol icmp accept
    }

    chain output {
        type filter hook output priority 0; policy drop;
	oif lo accept

        # Conexiones ya establecidas o relacionadas
        ct state established,related accept

	# SSH, HTTP, HTTPS, CORREO, DNS
        tcp dport 22 ct state new accept
        tcp dport 25 ct state new accept
        tcp dport 80 ct state new accept
        tcp dport 443 ct state new accept
        udp dport 53 ct state new accept
        tcp dport 53 ct state new accept

	# Logs a Anubis
        ip daddr 172.16.0.200 tcp dport 514 ct state new accept
        ip daddr 172.16.0.200 udp dport 514 accept

        # Ping y traceroute
        ip protocol icmp accept
    }

chain forward {
        type filter hook forward priority filter; policy drop;

        # Permitir salida a Internet para contenedores Docker
        ip saddr 172.16.0.0/12 oifname "eth0" accept

        # Permitir tráfico de respuesta
        iifname "eth0" ip daddr 172.16.0.0/12 ct state established,related accept

        # Permitir comunicación entre contenedores
        ip saddr 172.16.0.0/12 ip daddr 172.16.0.0/12 accept
    }
}

# NAT para contenedores Docker
table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100; policy accept

        # Mascarade para todas las redes Docker, se mejora en cambio IV para alcanzar más redes creadas para contenedores
        oifname "eth0" ip saddr 172.16.0.0/12 masquerade
    }
}
