#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        iif lo accept
	ct state established,related accept

        # SSH, DNS
        tcp dport 22 ct state new accept
        udp dport 53 ct state new accept
        tcp dport 53 ct state new accept
	ip protocol icmp icmp type echo-request accept
    }

    chain output {
        type filter hook output priority 0; policy drop;
	oif lo accept
	ct state established,related accept

        # SSH, DNS, HTTP, HTTPS
        tcp dport 22 ct state new accept
        udp dport 53 ct state new accept
        tcp dport 53 ct state new accept
        tcp dport 80 ct state new accept
        tcp dport 443 ct state new accept

	# Permitir enviar logs al servidor central Anubis
	ip daddr 172.16.0.200 udp dport 514 accept
	ip daddr 172.16.0.200 tcp dport 514 ct state new accept

	# ICMP saliente para ping y traceroute
        ip protocol icmp accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }
}
